### ISSUE TITLE
[SCREEN] Mentor Screen 

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#26]
The mentor has these widgets under the folder. These need to be added to a single `MentorScreen`.

```
mentor/
   ├── widgets
         ├── mentor_preview_widget.dart
         ├── mentor_widget_extended.dart
```

<br>

<table>
        <tr>
          <td>
            <img src="https://user-images.githubusercontent.com/53579386/135633039-0b4eb1b4-5735-46c2-89af-49837bd7d0a2.jpeg" alt="">
          </td>
          <td>
            <img src="https://user-images.githubusercontent.com/53579386/135633034-2ef611b6-0471-42ab-a0b9-6ed9f9aa7b05.jpeg" alt="">
          </td>
        </tr>
 </table>

![designs](https://user-images.githubusercontent.com/53579386/135633300-d13e9bd0-53dd-4dfe-a978-77a221987518.png)

### Tasks to do:

- [ ] Add a scrollable tab with horizontal scroll.
- [ ] Add extended widgets in vertical scroll.
- [ ] Also, need to make it reponsive.

**Comment by msramesh2k1** [comment]
Can I work on this issue? @adityathakurxd

**Comment by adityathakurxd** [comment]
Hey @msramesh2k1, Sure please go ahead 🚀
This involves some redesigning. The two widgets are available although if you'll look at the designs, you'll see one of them needs to have Column like alignment.

Also, square config on both would be good.

**Comment by up4154** [comment]
hey can i work on this isseue

**Comment by adityathakurxd** [comment]
`hacktoberfest-accepted` label is for PRs accepted. This is an issue.

> A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label.

This repository is in line with the [guidelines](https://hacktoberfest.digitalocean.com/resources/maintainers).

**Comment by msramesh2k1** [comment]
Got it I thought which has lab hacktoberfest-accepted is the one under hacktoberfest 👍 @adityathakurxd

**Comment by msramesh2k1** [comment]
Hey @adityathakurxd , what should be the branch name , whether my username or feature name ??
