### ISSUE TITLE
[SCREEN] Modify Home

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/university#41]
The present home screen has only tiles showing up in a column.
Need to make it more modern and sort of with more options.

**I am thinking something like:**
(the first 'Explore Courses' like Screen)

<img width="3200" alt="Course Design Image" src="https://user-images.githubusercontent.com/53579386/135950217-7f5467e7-cb41-48e7-b04d-d5f49b7b6f8b.png">

This but we have:
- The tiles or custom home widget show up in a row fashion without any shadow under 'Popular Courses', and
- A Mentor of the week section with Image, Name, and Description without the + icon.
 
Also, I have no immediate plans of adding course preview images.

**Comment by Power-PP** [comment]
Is this issue still open? if yes, can you please elaborate more on this

**Comment by adityathakurxd** [comment]
Sure please go ahead @Power-PP 

The app's homepage right now is very basic and looks something like this:
![WhatsApp Image 2021-10-04 at 10 17 37 AM](https://user-images.githubusercontent.com/53579386/135958004-1e47a5a3-58e3-46c5-a6eb-306825f8c7d1.jpeg)

Your task would be too:

- [ ] Add an 'Explore Roadmaps' text as is 'Popular Courses' in this [design](https://github.com/adityathakurxd/university/issues/41#issue-1015815751).
- [ ] Remove the shadow effect from the custom home widget so it looks more on screen.
- [ ] Make these in a horizontal scroll fashion as are the different course tiles in this [design](https://github.com/adityathakurxd/university/issues/41#issue-1015815751).
- [ ] Add a 'Mentor of Week' text.
- [ ] Add the Mentor tiles as in the [design ](https://github.com/adityathakurxd/university/issues/41#issue-1015815751)with only Image, Name, and a Title text. The + icon is not necessary.

That would do! Also, do attach a screenshot of your work with the PR. 
Thanks and All the best. 🎉 If you have any questions, feel free to tag me here or on Discord (Link: [https://teamaditya.co/](https://teamaditya.co/))

**Comment by Power-PP** [comment]
Just to confirm will all this will be a single pull request?

**Comment by adityathakurxd** [comment]
Yes. Adding multiple PRs for a single screen might not be apt. 
I explained it at length, although the issue just involves using some text widgets and wrapping with a scroll view.

**Comment by Power-PP** [comment]
Alright
